# Generated by Django 5.2.5 on 2025-08-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='comedores/')),
                ('barrio', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
            ],
        ),
    ]
