# Generated by Django 5.2.5 on 2025-08-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedor',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
