# Generated by Django 5.2.5 on 2025-09-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pendingregistration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingRegistration',
        ),
    ]
