# Generated by Django 5.2.5 on 2025-09-25 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_pendingregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo_donacion', models.IntegerField()),
                ('comedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comedor')),
            ],
        ),
        migrations.CreateModel(
            name='PublicacionArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_articulo', models.CharField(max_length=255)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicacion')),
            ],
            options={
                'unique_together': {('publicacion', 'nombre_articulo')},
            },
        ),
    ]
