# Generated by Django 5.2.6 on 2025-09-30 02:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_pendingregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPublicacion',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=255)),
            ],
            options={
                'db_table': 'TipoPublicacion',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('id_comedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comedor')),
                ('id_tipo_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipopublicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.AutoField(db_column='IdDonacion', primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_comedor', models.ForeignKey(db_column='IdComedor', on_delete=django.db.models.deletion.CASCADE, to='core.comedor')),
                ('id_usuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
                ('id_publicacion', models.ForeignKey(db_column='IdPublicacion', on_delete=django.db.models.deletion.CASCADE, to='core.publicacion')),
            ],
            options={
                'db_table': 'Donacion',
            },
        ),
        migrations.CreateModel(
            name='DonacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_articulo', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('id_donacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.donacion')),
            ],
            options={
                'unique_together': {('id_donacion', 'nombre_articulo')},
            },
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(db_column='FechaAlta')),
                ('id_comedor', models.ForeignKey(db_column='IdComedor', on_delete=django.db.models.deletion.CASCADE, to='core.comedor')),
                ('id_usuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
            options={
                'db_table': 'Favoritos',
                'unique_together': {('id_usuario', 'id_comedor')},
            },
        ),
        migrations.CreateModel(
            name='PublicacionArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_articulo', models.CharField(max_length=255)),
                ('id_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicacion')),
            ],
            options={
                'unique_together': {('id_publicacion', 'nombre_articulo')},
            },
        ),
    ]
