# Generated by Django 5.2.5 on 2025-09-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tipopublicacion_publicacion_donacion_donacionitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritos',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True, db_column='FechaAlta'),
        ),
    ]
