# Generated by Django 5.2.5 on 2025-09-27 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_publicacion_publicacionarticulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(db_column='FechaAlta')),
                ('id_comedor', models.ForeignKey(db_column='IdComedor', on_delete=django.db.models.deletion.CASCADE, to='core.comedor')),
                ('id_usuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
            options={
                'db_table': 'Favoritos',
                'unique_together': {('id_usuario', 'id_comedor')},
            },
        ),
    ]
