# Generated by Django 5.2.5 on 2025-09-27 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_favoritos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDonacion',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=255)),
            ],
            options={
                'db_table': 'TipoDonacion',
            },
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.AutoField(db_column='IdDonacion', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='Titulo', max_length=255)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=255)),
                ('id_usuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
                ('id_tipodonacion', models.ForeignKey(db_column='IdTipoDonacion', on_delete=django.db.models.deletion.CASCADE, to='core.tipodonacion')),
            ],
            options={
                'db_table': 'Donacion',
            },
        ),
    ]
