# Generated by Django 5.2.6 on 2025-10-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comedor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='telefono',
            field=models.CharField(blank=True, db_column='Telefono', max_length=20, null=True),
        ),
    ]
